VersionTwo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('accounts/', include('accounts.urls')),
]

handler404 = 'tracker.views.handler404'
handler500 = 'tracker.views.handler500'

tracker/urls.py
from django.conf.urls.static import static

from VersionTwo import settings
from tracker.views import ProjectNew, ProjectsList, ProjectInfo, ProjectDelete, ProjectEdit, ColumnNew, ColumnInfo, \
    ColumnDelete, ColumnEdit, BugReport, BugReportList, CategoryList, TaskList, TaskCreate, TaskInfo, TaskDelete
from . import views
from django.urls import path

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='home'),
    path('projects/', ProjectsList.as_view(), name='projects'),
    path('projects/new/', ProjectNew.as_view(), name='project_new'),
    path('projects/<int:project_id>/', ProjectInfo.as_view(), name='project_info'),
    path('projects/<int:project_id>/delete/', ProjectDelete.as_view(), name='project_delete'),
    path('projects/<int:project_id>/edit/', ProjectEdit.as_view(), name='project_edit'),
    path('categories/', CategoryList.as_view(), name='column_list'),
    path('categories/new/', ColumnNew.as_view(), name='column_new'),
    path('categories/<int:category_id>/', ColumnInfo.as_view(), name='column_info'),
    path('categories/<int:category_id>/delete', ColumnDelete.as_view(), name='column_delete'),
    path('categories/<int:category_id>/edit', ColumnEdit.as_view(), name='column_edit'),
    path('bug_report/', BugReport.as_view(), name='bug_report'),
    path('bug_list/', BugReportList.as_view(), name='bug_report_list'),
    path('tasks/', TaskList.as_view(), name='task_list'),
    path('tasks/<int:task_id>/', TaskInfo.as_view(), name='task_info'),
    path('tasks/create', TaskCreate.as_view(), name='task_create'),
    path('tasks/<int:task_id>/delete', TaskDelete.as_view(), name='task_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'views.handler404'

templates/projects/create.html
{% extends 'adminlte/base.html' %}

{% block title %}Project Create{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <!-- /.login-logo -->
                <div class="box-header with-border">
                    <h3 class="box-title">Project Create</h3>
                </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                            <h2>New Project</h2>
                                    <div class="form-group has-feedback">
                                        <input required name="name" class="form-control" placeholder="Project Name">
                                        <span class="fa fa-file form-control-feedback"></span>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <textarea name="description" rows="5" class="form-control" placeholder="Project Description" style="resize: none"></textarea>
                                        <span class="glyphicon glyphicon-align-left form-control-feedback"></span>
                                    </div>
                            <div class="box-footer">
                                <div class="row">
                                    <div class="col-xs-8">
                                    </div>
                                    <div class="col-xs-4">
                                        <button type="submit" class="btn btn-primary btn-block btn-flat">Create</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Project Info</h3>
                </div>
                <div class="box-body">
                    <h3>What is project?</h3>
                    <p style="font-size: large">
                        A project is an abstraction that will contain categories that in turn contain your tasks.</p>
                    <hr>
                    <h3>For what?</h3>
                    <p style="font-size: large">
                        Tasks from different areas of life can be confusing and difficult to control and organize all
                        the information. The categories in which tasks could be stored also do not completely solve
                        the problem, because the categories "Music" and "Scientific work" on one screen can interfere
                        with each other. To do this, there is an abstraction "Project", which in turn contains
                        categories and allows thematically or in the sense of separate categories from each other.
                    </p>
                    <hr>
                    <h3>Example of use</h3>
                    <p style="font-size: large">
                        - Project "Business", which contains all the tasks related to the opening and operation
                        of the business.<br>
                        - Project "University", where you can store all your homework, compound tasks for scientific
                        papers and other tasks.<br>
                        - The project "Learning English", which will contain all the tasks related to the study of
                        a foreign language.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/projects/delete.html
{% extends 'adminlte/base.html' %}

{% block title %}{{ project.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center align-middle">
                <h2>Are you sure you want to delete the project? <br>After confirmation, you can not restore it in any way</h2>
                <div class="col-md-6">
                    <a href="{% url 'tracker:project_info' project.id %}" class="btn btn-block btn-primary btn-lg">Undo</a>
                </div>
                <form action="" method="post">
                    <div class="col-md-6">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-danger btn-lg">Delete</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/projects/edit.html
{% extends 'adminlte/base.html' %}

{% block title %}{{ project.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center">
                <h2>Enter a title and description for the project</h2>
                <div class="col-md-6">
                </div>
                <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                                    <div class="form-group has-feedback">
                                        <input type="text" required name="name" class="form-control" placeholder="Project Name" value="{{ project.name }}">
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <textarea name="description" rows="5" class="form-control" placeholder="Project Description" style="resize: none">{{ project.description }}</textarea>
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                            <div class="col-xs-8">
                            </div>
                            <div class="col-xs-4">
                                <button type="submit" class="btn btn-primary btn-block btn-block">Save</button>
                            </div>
                        </div>
                    </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/projects/info.html
{% extends 'adminlte/base.html' %}

{% block title %}Takinata web. {{ project.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Main Information</h3>
                    </div>
                    <div class="box-body">
                        <p><b>Title: </b>{{ project.name }}</p>
                        <p><b>Description: </b>{{ project.description }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Manage Project</h3>
                    </div>
                    <div class="box-body">
                        <a href="{% url 'tracker:project_edit' project.id %}" class="btn btn-block btn-primary">Edit</a>
                        <a href="{% url 'tracker:project_delete' project.id %}"
                           class="btn btn-block btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"
                            style="vertical-align: middle; display: inline-block; margin: 10px"> Categories</h3>
                    </div>
                    <div class="box-body">
                        {% for category in categories %}
                            <a style="color: #000000" class="text"
                               href="{% url 'tracker:column_info' category.id %}"><h4>{{ category.name }}</h4>
                            </a>
                        {% endfor %}
                        {% if not categories %}
                            <h4>There is no columns in this project</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title" style="vertical-align: middle; display: inline-block; margin: 10px">
                            Tasks</h3>
                    </div>
                    <div class="box-body">
                        {% for task in tasks %}
                            {% if task.is_archive != 1 %}
                                <a style="color: #000000" class="text"
                                   href="{% url 'tracker:task_info' task.id %}">
                                    <h4>{{ task.name }}</h4>
                                </a>
                            {% else %}
                                <a style="color: #000000" class="text"
                                   href="{% url 'tracker:task_info' task.id %}">
                                    <h4><s>{{ task.name }}</s></h4>
                                </a>
                            {% endif %}
                        {% endfor %}
                        {% if not tasks %}
                            <h4>There is no tasks in this project</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Members</h3>
                    </div>
                    <div class="box-body">
                        <h4>Creator:</h4>
                        <p>{{ creator.username }}</p>
                        <h4>Executors:</h4>
                        {% for user in guys %}
                            <td>{{ user.username }}</td>
                            <br>
                        {% endfor %}
                    </div>
                </div>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Executors dashboard</h3>
                    </div>
                    <div class="box-body">
                        <form role="form" method="post">
                            {% csrf_token %}
                            <div class="row">
                                {% if guys %}
                                    <div class="form-group">
                                        <row>
                                            <div class="col-md-12">
                                                <label>Remove from project: </label>
                                            </div>
                                        </row>
                                        <row>
                                            <div class="col-md-5">
                                                <label>
                                                    <select style="display: inline-block"
                                                            class="form-control js-example-basic-single"
                                                            name="remove_select" id="remove_select">
                                                        {% for user in guys %}
                                                            <option>{{ user.username }}</option>
                                                        {% endfor %}
                                                    </select>
                                                </label>
                                            </div>
                                            <div class="col-md-5 pull-right">
                                                <button type="submit" name='remove_from_project'
                                                        class="btn btn-primary btn-block">Remove
                                                </button>
                                            </div>
                                        </row>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="row">
                                <div class="form-group">
                                        <row>
                                            <div class="col-md-12">
                                                <label>Add to project: </label>
                                            </div>
                                        </row>
                                        <row>
                                            <div class="col-md-5">
                                                <label>
                                                    <input name="add_select" class="form-control"
                                                           placeholder="username">
                                                </label>
                                            </div>
                                            <div class="col-md-5 pull-right">
                                                <button type="submit" name="add_to_project"
                                                        class="btn btn-primary btn-block">Add
                                                </button>
                                            </div>
                                        </row>
                                    </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $("#remove_select").select2({width: 'resolve'});
        });
    </script>
{% endblock %}

templates/projects/list.html
{% extends 'adminlte/base.html' %}

{% block title %}List of Projects{% endblock %}
{% load i18n static %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <h1 class="page-header">List of projects</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <a href="{% url 'tracker:project_new' %}"><button class="btn btn-primary btn-block btn-block">Create project</button></a>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                {% if not project_list %}
                    <h1 class="text-center">There is no projects</h1>
                {% endif %}
                {% for project in project_list %}
                    <div class="col-md-6">
                        <div class="project" id="project.id">
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title"><a href="{% url 'tracker:project_info' project_id=project.id %}">{{ project.name }}</a></h3>
                                </div>
                                {% if project.description %}
                                    <div class="box-body">
                                        <p class="info">{{ project.description }}</p>
                                    </div>
                                {% endif %}
                                <div class="box-footer">
                                     <div class="row">
                                            <div class="col-md-4 pull-right">
                                                <a href="{% url 'tracker:project_info' project_id=project.id %}">
                                                    <button class="btn btn-primary btn-block btn-block">More Info</button>
                                                </a>
                                            </div>
                                     </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}