VersionTwo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('accounts/', include('accounts.urls')),
]

handler404 = 'tracker.views.handler404'
handler500 = 'tracker.views.handler500'

tracker/urls.py
from django.conf.urls.static import static

from VersionTwo import settings
from tracker.views import ProjectNew, ProjectsList, ProjectInfo, ProjectDelete, ProjectEdit, ColumnNew, ColumnInfo, \
    ColumnDelete, ColumnEdit, BugReport, BugReportList, CategoryList, TaskList, TaskCreate, TaskInfo, TaskDelete
from . import views
from django.urls import path

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='home'),
    path('projects/', ProjectsList.as_view(), name='projects'),
    path('projects/new/', ProjectNew.as_view(), name='project_new'),
    path('projects/<int:project_id>/', ProjectInfo.as_view(), name='project_info'),
    path('projects/<int:project_id>/delete/', ProjectDelete.as_view(), name='project_delete'),
    path('projects/<int:project_id>/edit/', ProjectEdit.as_view(), name='project_edit'),
    path('categories/', CategoryList.as_view(), name='column_list'),
    path('categories/new/', ColumnNew.as_view(), name='column_new'),
    path('categories/<int:category_id>/', ColumnInfo.as_view(), name='column_info'),
    path('categories/<int:category_id>/delete', ColumnDelete.as_view(), name='column_delete'),
    path('categories/<int:category_id>/edit', ColumnEdit.as_view(), name='column_edit'),
    path('bug_report/', BugReport.as_view(), name='bug_report'),
    path('bug_list/', BugReportList.as_view(), name='bug_report_list'),
    path('tasks/', TaskList.as_view(), name='task_list'),
    path('tasks/<int:task_id>/', TaskInfo.as_view(), name='task_info'),
    path('tasks/create', TaskCreate.as_view(), name='task_create'),
    path('tasks/<int:task_id>/delete', TaskDelete.as_view(), name='task_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'views.handler404'

templates/categories/column.html
{% extends 'adminlte/base.html' %}

{% block title %}{{ column.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Main Information</h3>
                    </div>
                    <div class="box-body">
                        <p><b>Title: </b>{{ column.name }}</p>
                        <p><b>Description: </b>{{ column.desc }}</p>
                        <p><b>Project : </b>{{ project.name }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tasks</h3>
                    </div>
                    <div class="box-body">
                        <p>'list'</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Manage Column</h3>
                    </div>
                    <div class="box-body">
                        <a href="{% url 'tracker:column_edit' project.id column.id %}" class="btn btn-block btn-warning">Edit</a>
                        <a href="{% url 'tracker:column_delete' project.id column.id%}" class="btn btn-block btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/categories/column_delete.html
{% extends 'adminlte/base.html' %}

{% block title %}{{ column.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center">
                <h2>Are you sure you want to delete the column? <br>After confirmation, you can not restore it in any way</h2>
                <div class="col-md-6">
                    <a href="{% url 'tracker:column_info' project.id column.id %}" class="btn btn-block btn-primary btn-lg">Undo</a>
                </div>
                <form action="" method="post">
                    <div class="col-md-6">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-danger btn-lg">Delete</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/categories/column_edit.html
{% extends 'adminlte/base.html' %}

{% block title %}{{ column.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center">
                <h2>Enter a title and description for the column</h2>
                <div class="col-md-6">
                </div>
                <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                                    <div class="form-group has-feedback">
                                        <input type="text" name="name" class="form-control" placeholder="Project Name" value="{{ column.name }}">
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <textarea name="description" rows="5" class="form-control" placeholder="Project Description" style="resize: none">{{ column.desc }}</textarea>
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                            <div class="col-xs-8">
                            </div>
                            <div class="col-xs-4">
                                <button type="submit" class="btn btn-primary btn-block btn-flat">Save</button>
                            </div>
                        </div>
                    </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/categories/column_new.html
{% extends 'adminlte/base.html' %}

{% block title %}Category Create{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <!-- /.login-logo -->
                <div class="box-header with-border">
                    <h3 class="box-title">Column Create</h3>
                </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                            <h2>New Column</h2>
                                    <div class="form-group has-feedback">
                                        <input name="name" class="form-control" placeholder="Column Name">
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <textarea name="description" rows="5" class="form-control" placeholder="Column Description" style="resize: none"></textarea>
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                            <label>
                                <select class="form-control js-example-basic-single" name="select_project">
                                    {% for project in projects %}
                                        <option>{{ project.name }}</option>
                                    {% endfor %}
                                </select>
                            </label>
                            <div class="box-footer">
                                <div class="row">
                                    <div class="col-xs-8">
                                    </div>
                                    <div class="col-xs-4">
                                        <button type="submit" class="btn btn-primary btn-block btn-flat">Create</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Column Info</h3>
                </div>
                <div class="box-body">
                    <h2>Kek</h2>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/categories/columns.html
{% extends 'adminlte/base.html' %}

{% block title %}List of Categories{% endblock %}
{% load i18n static %}

{% block content %}
    <section class="content-header">
        <h1>List of columns</h1>
    </section>
    <div class="container-fluid">
        <section class="content">
            <div class="row">
                {% for column in column_list %}
                    <div class="col-md-6">
                        <div class="project" id="project.id">
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title"><a href="{% url 'tracker:column_info' column_id=column.id project_id=column.project_id %}">{{ column.name }}</a></h3>
                                </div>
                                <div class="box-body">
                                    <p class="info">{{ column.desc }}</p>
                                </div>
                                <div class="box-footer">
                                     <div class="row">
                                            <div class="col-md-4 pull-right">
                                                <a href="{% url 'tracker:column_info' column_id=column.id project_id=column.project_id %}">
                                                    <button class="btn btn-primary btn-block btn-flat">More Info</button>
                                                </a>
                                            </div>
                                     </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock %}

templates/categories/create.html
{% extends 'adminlte/base.html' %}

{% block title %}Category Create{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <!-- /.login-logo -->
                <div class="box-header with-border">
                    <h3 class="box-title">Category Create</h3>
                </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                            <h2>New Category</h2>
                            <div class="form-group has-feedback">
                                <input required name="name" class="form-control" placeholder="Category Name">
                                <span class="fa fa-file form-control-feedback"></span>
                            </div>
                            <div class="form-group has-feedback">
                                <textarea name="description" rows="5" class="form-control" placeholder="Category Description" style="resize: none"></textarea>
                                <span class="glyphicon glyphicon-align-left form-control-feedback"></span>
                            </div>
                            <label>
                                {% if projects %}
                                    <select class="form-control js-example-basic-single" name="select_project">
                                        {% for project in projects %}
                                            <option value="{{ project.id }}">{{ project.name }}</option>
                                        {% endfor %}
                                    </select>
                                {% elif project %}
                                    <select class="form-control js-example-basic-single" name="select_project">
                                        <option>{{ project.name }}</option>
                                    </select>
                                 {% else %}
                                    <h3>There is no project to add category</h3>
                                {% endif %}
                            </label>
                            <div class="box-footer">
                                <div class="row">
                                    <div class="col-xs-8">
                                    </div>
                                    <div class="col-xs-4">
                                        {% if projects or project %}
                                            <button type="submit" class="btn btn-primary btn-block btn-flat">Create</button>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Category Info</h3>
                </div>
                <div class="box-body">
                    <h3>What is category?</h3>
                    <p style="font-size: large">
                        A category is a set of tasks grouped by one topic or area.</p>
                    <hr>
                    <h3>For what?</h3>
                    <p style="font-size: large">
                        Categories are designed to group tasks on some basis. For example, the task of "doing homework"
                        and "Buy notebooks" both belong to the project "Study", but to put them in the same semantic
                        group will not be correct. And storage task "mow the lawn" to "redecorate bedroom" in one
                        category of "House" is very strange. But the items "brush your teeth" and" prepare Breakfast
                        "can be safely placed in the category of "Daily routine".
                    </p>
                    <hr>
                    <h3>Example of use</h3>
                    <p style="font-size: large">
                        - Category "Scientific work" in the project "Study", which will contain tasks that will bring
                        you closer to writing a scientific work at the University.<br>
                        - Category " Car "in the project "Life", which will contain tasks related to your iron horse,
                        like "change oil", "call for maintenance", etc.<br>
                        - Category "Daily routine", which will contain all sorts of tasks that people perform every day,
                        like "brush your teeth", walk the dog" and the like.<br>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/categories/delete.html
{% extends 'adminlte/base.html' %}

{% block title %}Takinata web{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center">
                <h2>Are you sure you want to delete the column? <br>After confirmation, you can not restore it in any way</h2>
                <div class="col-md-6">
                    <a href="{% url 'tracker:column_info' category.id %}" class="btn btn-block btn-primary btn-lg">Undo</a>
                </div>
                <form action="" method="post">
                    <div class="col-md-6">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-danger btn-lg">Delete</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/categories/edit.html
{% extends 'adminlte/base.html' %}

{% block title %}Takinata web{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center">
                <h2>Enter a title and description for the column</h2>
                <div class="col-md-6">
                </div>
                <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                                    <div class="form-group has-feedback">
                                        <input type="text" name="name" class="form-control" placeholder="Project Name" value="{{ category.name }}">
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <textarea name="description" rows="5" class="form-control" placeholder="Project Description" style="resize: none">{{ category.desc }}</textarea>
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                            <div class="col-xs-8">
                            </div>
                            <div class="col-xs-4">
                                <button type="submit" class="btn btn-primary btn-block btn-flat">Save</button>
                            </div>
                        </div>
                    </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/categories/info.html
{% extends 'adminlte/base.html' %}

{% block title %}Takinata web. {{ category.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Main Information</h3>
                    </div>
                    <div class="box-body">
                        <p><b>Title: </b>{{ category.name }}</p>
                        <p><b>Description: </b>{{ category.desc }}</p>
                        <p><b>Project : </b>
                            <a href="{% url 'tracker:project_info' project.id %}">{{ project.name }}</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tasks</h3>
                    </div>
                    <div class="box-body">
                        {% for task in tasks %}
                            <a style="color: #000000" class="text" href="{% url 'tracker:task_info' task.id%}"><h4>{{ task.name }}</h4></a>
                        {% endfor %}
                        {% if not tasks %}
                            <h4>There is no tasks in this category</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Manage Column</h3>
                    </div>
                    <div class="box-body">
                        <a href="{% url 'tracker:column_edit' category.id %}" class="btn btn-block btn-primary">Edit</a>
                        <a href="{% url 'tracker:column_delete' category.id%}" class="btn btn-block btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/categories/list.html
{% extends 'adminlte/base.html' %}

{% block title %}List of Categories{% endblock %}
{% load i18n static %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <h1 class="page-header">List of categories</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <a href="{% url 'tracker:column_new' %}">
                        <button class="btn btn-primary btn-block">Create category</button>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <div class="container-fluid">
        <section class="content">
            <div class="row">
                {% if not category_list %}
                    <h1 class="text-center">There is no categories</h1>
                {% endif %}
                {% for category in category_list %}
                    <div class="col-md-6">
                        <div class="project" id="project.id">
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title"><a
                                            href="{% url 'tracker:column_info' category_id=category.id %}">{{ category.name }}</a>
                                    </h3>
                                </div>
                                {% if category.desc %}
                                    <div class="box-body">
                                        <p class="info">{{ category.desc }}</p>
                                    </div>
                                {% endif %}
                                <div class="box-footer">
                                    <div class="row">
                                        <div class="col-md-4 pull-right">
                                            <a href="{% url 'tracker:column_info' category_id=category.id %}">
                                                <button class="btn btn-primary btn-block">More Info</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock %}