VersionTwo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('accounts/', include('accounts.urls')),
]

handler404 = 'tracker.views.handler404'
handler500 = 'tracker.views.handler500'

accounts/urls.py
from . import views
from django.urls import path
from django.views.generic.base import RedirectView



app_name = 'accounts'
urlpatterns = [
    path('signin/', views.SignIn.as_view(), name='signin'),
    path('signout/', views.SignOut.as_view(), name='signout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', RedirectView.as_view(pattern_name='accounts:signin'), name='login'),
    path('logout/', RedirectView.as_view(pattern_name='accounts:signout'), name='logout'),
    path('registration/', RedirectView.as_view(pattern_name='accounts:signup'), name='registration'),
]

tracker/urls.py
from django.conf.urls.static import static

from VersionTwo import settings
from tracker.views import ProjectNew, ProjectsList, ProjectInfo, ProjectDelete, ProjectEdit, ColumnNew, ColumnInfo, \
    ColumnDelete, ColumnEdit, BugReport, BugReportList, CategoryList, TaskList, TaskCreate, TaskInfo, TaskDelete
from . import views
from django.urls import path

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='home'),
    path('projects/', ProjectsList.as_view(), name='projects'),
    path('projects/new/', ProjectNew.as_view(), name='project_new'),
    path('projects/<int:project_id>/', ProjectInfo.as_view(), name='project_info'),
    path('projects/<int:project_id>/delete/', ProjectDelete.as_view(), name='project_delete'),
    path('projects/<int:project_id>/edit/', ProjectEdit.as_view(), name='project_edit'),
    path('categories/', CategoryList.as_view(), name='column_list'),
    path('categories/new/', ColumnNew.as_view(), name='column_new'),
    path('categories/<int:category_id>/', ColumnInfo.as_view(), name='column_info'),
    path('categories/<int:category_id>/delete', ColumnDelete.as_view(), name='column_delete'),
    path('categories/<int:category_id>/edit', ColumnEdit.as_view(), name='column_edit'),
    path('bug_report/', BugReport.as_view(), name='bug_report'),
    path('bug_list/', BugReportList.as_view(), name='bug_report_list'),
    path('tasks/', TaskList.as_view(), name='task_list'),
    path('tasks/<int:task_id>/', TaskInfo.as_view(), name='task_info'),
    path('tasks/create', TaskCreate.as_view(), name='task_create'),
    path('tasks/<int:task_id>/delete', TaskDelete.as_view(), name='task_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'views.handler404'

templates/501.html
{% extends 'adminlte/base.html' %}

{% block title %}501. No permission{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <div class="row">
        <section class="content">
            <div class="error-page">
                <h2 class="headline text-yellow">501</h2>
                <div class="error-content">
                    <h3>
                        <i class="fa fa-warning text-yellow"></i>
                        "You have no permission!"
                    </h3>
                    <p>
                        "You have no permission to watch this page. For looking this page you need to authorize.
                        Meanwhile, you may
                        <a href="{% url 'accounts:registration' %}">sign up</a> or
                        <a href="{% url 'accounts:login' %}">sign in</a>.
                    </p>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/column_new.html
{% extends 'adminlte/base.html' %}

{% block title %}Project Create{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <!-- /.login-logo -->
                <div class="box-header with-border">
                    <h3 class="box-title">Column Create</h3>
                </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                            <h2>New Column</h2>
                                    <div class="form-group has-feedback">
                                        <input name="name" class="form-control" placeholder="Column Name">
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <textarea name="description" rows="5" class="form-control" placeholder="Column Description" style="resize: none"></textarea>
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                            <label>
                                <select class="form-control js-example-basic-single" name="select_project">
                                    {% for project in projects %}
                                        <option>{{ project.name }}</option>
                                    {% endfor %}
                                </select>
                            </label>
                            <div class="box-footer">
                                <div class="row">
                                    <div class="col-xs-8">
                                    </div>
                                    <div class="col-xs-4">
                                        <button type="submit" class="btn btn-primary btn-block btn-flat">Create</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Column Info</h3>
                </div>
                <div class="box-body">
                    <h2>Kek</h2>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'adminlte/base.html' %}
{% block title %}Takinata web{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content-header">
        <h1 class="text-center">Results of beta test</h1>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-xs-6">
                    <div class="small-box bg-yellow">
                        <div class="inner">
                            <h3>{{ users }}</h3>
                            <p>User Registrations</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-user-plus"></i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xs-6">
                    <div class="small-box bg-aqua">
                        <div class="inner">
                            <h3>{{ projects }}</h3>
                            <p>Projects Created</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-hdd-o"></i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xs-6">
                    <div class="small-box bg-green">
                        <div class="inner">
                            <h3>{{ categories }}</h3>
                            <p>Categories Created</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-folder-o"></i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xs-6">
                    <div class="small-box bg-red">
                        <div class="inner">
                            <h3>{{ tasks }}</h3>
                            <p>Tasks Created</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-save"></i>
                        </div>
                    </div>
                </div>
            </div>
            <h1 class="text-center">Notifications</h1>
            <div class="col-md-4">
                {% if red_list %}
                    <div class="alert alert-danger alert-dismissable">
                        <h4>
                            <i class="icon fa fa-ban"></i> Alert!
                        </h4>
                    </div>
                    <div class="box box-danger">
                        <div class="box-body">
                            {% for task in red_list %}
                                <p class="lead">
                                <td><a href="{% url 'tracker:task_info' task.id %}">{{ task.name }}</a> -
                                    Remaining {{ task.to_deadline }} days
                                </td>
                                </p>
                                <br>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-4">
                {% if yellow_list %}
                    <div class="alert alert-warning alert-dismissable">
                        <h4>
                            <i class="icon fa fa-warning"></i> Warning!
                        </h4>
                    </div>
                    <div class="box box-warning">
                        <div class="box-body">
                            {% for task in yellow_list %}
                                <p class="lead">
                                <td><a href="{% url 'tracker:task_info' task.id %}">{{ task.name }}</a> -
                                    Remaining {{ task.to_deadline }} days
                                </td>
                                </p>
                                <br>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-4">
                {% if green_list %}
                    <div class="alert alert-success alert-dismissable">
                        <h4>
                            <i class="icon fa fa-check"></i> Keep calm
                        </h4>
                    </div>
                    <div class="box box-success">
                        <div class="box-body">
                            {% for task in green_list %}
                                <p class="lead">
                                <td><a href="{% url 'tracker:task_info' task.id %}">{{ task.name }}</a> -
                                    Remaining {{ task.to_deadline }} days
                                </td>
                                </p>
                                <br>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
    <script src="https://unpkg.com/ionicons@4.3.0/dist/ionicons.js"></script>
{% endblock %}

templates/new_project.html
{% extends 'adminlte/base.html' %}

{% block title %}Project Create{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <!-- /.login-logo -->
                <div class="box-header with-border">
                    <h3 class="box-title">Project Create</h3>
                </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                            <h2>New Project</h2>
                                    <div class="form-group has-feedback">
                                        <input name="name" class="form-control" placeholder="Project Name">
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <textarea name="description" rows="5" class="form-control" placeholder="Project Description" style="resize: none"></textarea>
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                            <div class="box-footer">
                                <div class="row">
                                    <div class="col-xs-8">
                                    </div>
                                    <div class="col-xs-4">
                                        <button type="submit" class="btn btn-primary btn-block btn-flat">Create</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Project Info</h3>
                </div>
                <div class="box-body">
                    <h2>Kek</h2>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/no_permission.html
{% extends 'adminlte/base.html' %}

{% block title %}Project Create{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <div class="row">
        <section class="content">
            <div class="error-page">
                <h2 class="headline text-yellow">403</h2>
                <div class="error-content">
                    <h3>
                        <i class="fa fa-warning text-yellow"></i>
                        "You have no permission!"
                    </h3>
                    <p>
                        "You have no permission to watch this page. For looking this page you need to authorize.
                        Meanwhile, you may
                        <a href="{% url 'accounts:registration' %}">sign up</a> or
                        <a href="{% url 'accounts:login' %}">sign in</a>.
                    </p>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/project.html
{% extends 'adminlte/base.html' %}

{% block title %}{{ project.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Main Information</h3>
                    </div>
                    <div class="box-body">
                        <p><b>Title: </b>{{ project.name }}</p>
                        <p><b>Description: </b>{{ project.description }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Manage Project</h3>
                    </div>
                    <div class="box-body">
                        <a href="{% url 'tracker:project_edit' project.id %}" class="btn btn-block btn-warning">Edit</a>
                        <a href="{% url 'tracker:project_delete' project.id %}" class="btn btn-block btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Columns</h3>
                    </div>
                    <div class="box-body">
                        {% for column in columns %}
                            <a style="color: #000000" class="text" href="{% url 'tracker:column_info' project.id column.id %}"><h4>{{ column.name }}</h4></a>
                        {% endfor %}
                        {% if not columns %}
                            <h4>There is no columns in this project</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tasks</h3>
                    </div>
                    <div class="box-body">
                        <p>'list'</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Executors</h3>
                    </div>
                    <div class="box-body">
                       {% for user in guys %}
                           <td>{{ user.username }}</td>
                           <br>
                       {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8"></div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Executors dashboard</h3>
                    </div>
                    <div class="box-body">
                        <form role="form" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-xs-8">
                                    <label>Remove from project: </label>
                                    <label>
                                        <select class="form-control js-example-basic-single" name="remove_select">
                                        {% for user in guys %}
                                            <option>{{ user.username }}</option>
                                        {% endfor %}
                                        </select>
                                    </label>
                                    </div>
                                    <div class="col-xs-4">
                                        <button type="submit" name='remove_from_project' class="btn btn-primary btn-block btn-flat">OK</button>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-xs-8">
                                    <label>Add to project: </label>
                                    <label>
                                        <select class="form-control js-example-basic-single" name="add_select">
                                        {% for user in all_guys %}
                                            <option>{{ user.username }}</option>
                                        {% endfor %}
                                        </select>
                                    </label>
                                    </div>
                                    <div class="col-xs-4">
                                        <button type="submit" name="add_to_project" class="btn btn-primary btn-block btn-flat">OK</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/project_delete.html
{% extends 'adminlte/base.html' %}

{% block title %}{{ project.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center">
                <h2>Are you sure you want to delete the project? <br>After confirmation, you can not restore it in any way</h2>
                <div class="col-md-6">
                    <a href="{% url 'tracker:project_info' project.id %}" class="btn btn-block btn-primary btn-lg">Undo</a>
                </div>
                <form action="" method="post">
                    <div class="col-md-6">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-danger btn-lg">Delete</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/project_edit.html
{% extends 'adminlte/base.html' %}

{% block title %}{{ project.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center">
                <h2>Enter a title and description for the project</h2>
                <div class="col-md-6">
                </div>
                <form action="" method="post">
                        {% csrf_token %}
                        <div class="box-body">
                                    <div class="form-group has-feedback">
                                        <input type="text" name="name" class="form-control" placeholder="Project Name" value="{{ project.name }}">
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <textarea name="description" rows="5" class="form-control" placeholder="Project Description" style="resize: none">{{ project.description }}</textarea>
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                            <div class="col-xs-8">
                            </div>
                            <div class="col-xs-4">
                                <button type="submit" class="btn btn-primary btn-block btn-flat">Save</button>
                            </div>
                        </div>
                    </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/welcome.html
{% extends 'adminlte/base.html' %}

{% block title %}Site presentation{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row text-center" style="height: 550px">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <img src="{% static 'logo.png' %}" class="img-responsive center-block"/>
                    <h1 style="margin: 30px auto 0;max-width: 800px">
                        Takinata web - is a free, flexible and intuitive way to organize anything with anyone.
                    </h1>
                    <p style="display: block; max-width: 800px; color: #4d4d4d; font-weight: 300; line-height: 1.5;
                        font-family: 'Helvetica Neue',serif; margin-top: 30px;"
                       class="lead center-block">Throw away long chains of emails, outdated tables, not so sticky
                        stickers
                        and clumsy programs for project management. Trello helps to see all the details of the
                        project
                        at a glance.</p>
                    <a href="{% url 'accounts:registration' %}">
                        <button type="submit" class="btn btn-success" name="cancel_task"
                                style="margin-top: 20px; font-size: 30px">Register - it's free.
                        </button>
                    </a>
                    <p class="lead center-block" style="margin-top: 30px">or</p>
                    <a href="{% url 'accounts:login' %}"
                       style="text-decoration: underline; color: #727272; display: block;font-weight: 300; line-height: 1.5;
                           font-family: 'Helvetica Neue',serif;"
                       class="lead center-block">log
                        in...
                    </a>
                    <div class="col-md-3"></div>
                </div>
            </div>
            <div class="row text-center">
                <img src="{% static 'projects.png' %}" class="img-responsive" style="margin-top: 30px;"/>
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <p style="display: block; max-width: 800px; color: #4d4d4d; font-weight: 300; line-height: 1.5;
                        font-family: 'Helvetica Neue',serif; margin-top: 30px;"
                       class="lead center-block">This is a project window. Here is a list of all the projects that
                        the user created or in which he participates</p>
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row text-center">
                <img src="{% static 'project_info.png' %}" class="img-responsive" style="margin-top: 30px;"/>
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <p style="display: block; max-width: 800px; color: #4d4d4d; font-weight: 300; line-height: 1.5;
                        font-family: 'Helvetica Neue',serif; margin-top: 30px;"
                       class="lead center-block">This is the project window. Here you can create, delete project
                        executors, information about the project, and also see what tasks are currently active</p>
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row text-center">
                <img src="{% static 'task_info.png' %}" class="img-responsive" style="margin-top: 30px;"/>
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <p style="display: block; max-width: 800px; color: #4d4d4d; font-weight: 300; line-height: 1.5;
                        font-family: 'Helvetica Neue',serif; margin-top: 30px;"
                       class="lead center-block">This is the task window. Here you can look at the timing of the
                        task, update or delete it, associate it with another task if desired, if it is not regular,
                        for example. The task is the main abstraction of the tracker</p>
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row text-center">
                <div class="col-md-3"></div>
                <h1 style="margin: 30px auto 0;max-width: 800px">
                    Throw away stickers, tables, mail and clumsy programs for project management and become one of the
                    people who fell in love with Takinata. You can add as many projects and people as you want in your
                    account.
                </h1>
                <a href="{% url 'accounts:registration' %}">
                    <button type="submit" class="btn btn-success center-block" name="cancel_task"
                            style="margin-top: 20px; font-size: 30px">Register - it's free.
                    </button>
                </a>
                <div class="col-md-3"></div>
            </div>
        </div>
    </section>
{% endblock %}