VersionTwo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('accounts/', include('accounts.urls')),
]

handler404 = 'tracker.views.handler404'
handler500 = 'tracker.views.handler500'

tracker/urls.py
from django.conf.urls.static import static

from VersionTwo import settings
from tracker.views import ProjectNew, ProjectsList, ProjectInfo, ProjectDelete, ProjectEdit, ColumnNew, ColumnInfo, \
    ColumnDelete, ColumnEdit, BugReport, BugReportList, CategoryList, TaskList, TaskCreate, TaskInfo, TaskDelete
from . import views
from django.urls import path

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='home'),
    path('projects/', ProjectsList.as_view(), name='projects'),
    path('projects/new/', ProjectNew.as_view(), name='project_new'),
    path('projects/<int:project_id>/', ProjectInfo.as_view(), name='project_info'),
    path('projects/<int:project_id>/delete/', ProjectDelete.as_view(), name='project_delete'),
    path('projects/<int:project_id>/edit/', ProjectEdit.as_view(), name='project_edit'),
    path('categories/', CategoryList.as_view(), name='column_list'),
    path('categories/new/', ColumnNew.as_view(), name='column_new'),
    path('categories/<int:category_id>/', ColumnInfo.as_view(), name='column_info'),
    path('categories/<int:category_id>/delete', ColumnDelete.as_view(), name='column_delete'),
    path('categories/<int:category_id>/edit', ColumnEdit.as_view(), name='column_edit'),
    path('bug_report/', BugReport.as_view(), name='bug_report'),
    path('bug_list/', BugReportList.as_view(), name='bug_report_list'),
    path('tasks/', TaskList.as_view(), name='task_list'),
    path('tasks/<int:task_id>/', TaskInfo.as_view(), name='task_info'),
    path('tasks/create', TaskCreate.as_view(), name='task_create'),
    path('tasks/<int:task_id>/delete', TaskDelete.as_view(), name='task_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'views.handler404'

templates/tasks/create.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>

{% extends 'adminlte/base.html' %}
{% block title %}Task Create{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content-header">
        <h1>Task list</h1>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-primary">
                        <!-- /.login-logo -->
                        <div class="box-header with-border">
                            <h3 class="box-title">Task Create</h3>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                            <div class="box-body">
                                {% if message %}
                                    <p class="login-box-msg" style="color: red;">{{ message }}</p>
                                {% endif %}
                                {% if error %}
                                    <p class="alert alert-danger"> Error! {{ error }}</p>
                                {% endif %}
                                {% for field in form %}
                                    <div class="form-group has-feedback">
                                        {{ field }}
                                        {% if field.help_text %}
                                            <small style="color: grey">{{ field.help_text | safe }}</small>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <p style="color: red">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endfor %}
                                <row>
                                    <select id='select_type' class="form-control js-example-basic-single"
                                            name="select_type">
                                        <option selected="selected" value="1">One-time</option>
                                        <option value="2">Regular</option>
                                    </select>
                                    <div class="col-md-4" style="padding-left: 0px;">
                                        <p style="font-size: large">Priority: </p>
                                        <label>
                                            <select name="priority" class="form-control js-example-basic-single">
                                                <option>max</option>
                                                <option>medium</option>
                                                <option>min</option>
                                            </select>
                                        </label>
                                    </div>
                                    <div class="col-md-4">
                                        <p style="font-size: large">Project:</p>
                                        <label>
                                            {% if projects %}
                                                <select id='select_project' class="form-control js-example-basic-single"
                                                        name="select_project">
                                                    {% for project in projects %}
                                                        <option value={{ project.id }}>{{ project.name }}</option>
                                                    {% endfor %}
                                                </select>
                                            {% endif %}
                                            {% if project %}
                                                <select id='select_project' class="form-control js-example-basic-single"
                                                        name="select_project">
                                                    {% for project in projects %}
                                                        <option value={{ project.id }}>{{ project.name }}</option>
                                                    {% endfor %}
                                                </select>
                                            {% endif %}
                                        </label>
                                    </div>
                                    <div class="col-md-4" style="padding-right: 0px; padding-left: 20px">
                                        <p style="font-size: large">Category:</p>
                                        <label class="btn-block">
                                            <select id='select_column' class="form-control js-example-basic-single"
                                                    name="select_column">
                                                {% for category in categories %}
                                                    <option class="{{ category.project_id }}"
                                                            value={{ category.id }}>{{ category.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </label>
                                    </div>
                                </row>
                            </div>
                            <div class="box-footer">
                                <div class="row">
                                    <div class="col-md-8"></div>
                                    <div class="col-md-4">
                                        <button type="submit" class="btn btn-primary btn-block btn-flat">Create</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Task info</h3>
                        </div>
                        <div class="box-body">
                            <h3>What is task?</h3>
                            <p style="font-size: large">
                                A task is some action that you want to do in the future.</p>
                            <hr>
                            <h3>For what?</h3>
                            <p style="font-size: large">
                                The modern world lives very quickly and there are always a lot of tasks that need to be
                                quickly written down so as not to forget. It can be all sorts of tasks, ranging from
                                simple, like "buy products", ending with some "build a house." The ability to create
                                and store anywhere a task will help not forget to do important things.
                            </p>
                            <hr>
                            <h3>Example of use</h3>
                            <p style="font-size: large">
                                - The task "Buy products" can contain in the description a list of everything you
                                need to buy for dinner.<br>
                                - The task "Make a homework" can contain in the description a list of subjects and
                                tasks for them that you need to accomplish by a certain date.<br>
                                - The "Contact with organizers" task allows you to store in the description the names
                                and numbers of those people who need to call.<br>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $('#select_column').prop('disabled', 'disabled');
        var $selected_column = $('#select_column'),
            $options = $selected_column.find('option');
        $(document).ready(function () {
        });
        $(document).ready(function () {
            $('#select_project').on("select2:select", function (e) {
                $selected_column.html($options.filter('[class="' + this.value + '"]'));
                {#$('#select_column').parent().show();#}
                $("#select_column").prop("selectedIndex", -1);
                $('#select_column').prop('disabled', false);
            });
        });
        $("#select_project").prop("selectedIndex", -1);
        $("#select_column").prop("selectedIndex", -1);
    </script>
{% endblock %}

templates/tasks/delete.html
{% extends 'adminlte/base.html' %}

{% block title %}Delete {{ task.name }}{% endblock %}
{% load i18n static %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5 text-center">
                <h2>Are you sure you want to delete the task? <br>After confirmation, you can not restore it in any way</h2>
                <div class="col-md-6">
                    <a href="{% url 'tracker:task_info' task.id%}" class="btn btn-block btn-primary btn-lg">Undo</a>
                </div>
                <form action="" method="post">
                    <div class="col-md-6">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-danger btn-lg">Delete</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>
{% endblock %}

templates/tasks/info.html
{% extends 'adminlte/base.html' %}

{% block title %}Takinata web. {{ task.name }}{% endblock %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Main Information</h3>
                    </div>
                    <div class="box-body">
                        <div class="col-md-6">
                            <p style="font-size: medium"><b>Title: </b>{{ task.name }}</p>
                            <p style="font-size: medium"><b>Description: </b>{{ task.desc }}</p>
                            {% if project %}
                                <p style="font-size: medium"><b>Project : </b>
                                    <a href="{% url 'tracker:project_info' task.project_id %}">{{ project.name }}</a>
                                </p>
                                <p style="font-size: medium"><b>Category : </b>
                                    <a href="{% url 'tracker:column_info' task.category_id %}">{{ category.name }}</a>
                                </p>
                            {% endif %}
                            <p style="font-size: medium"><b>Type: </b>
                                {% if task.type == 1 %}
                                    One-time
                                {% else %}
                                    Regular
                                {% endif %}
                            </p>
                            {% if task.type == 2 %}
                                <p style="font-size: medium"><b>Period: </b>
                                    {{ task.period }} days
                                </p>
                            {% endif %}
                            {% if task.assosiated_task_id != None %}
                                <p style="font-size: medium"><b>Assosiated with: </b>
                                    <a href="{% url 'tracker:task_info' a_task.id %}">{{ a_task.name }}</a>
                                </p>
                            {% endif %}
                            {% if parent %}
                                <p style="font-size: medium"><b>Parent task: </b>
                                    <a href="{% url 'tracker:task_info' parent.id %}">{{ parent.name }}</a>
                                </p>
                            {% endif %}
                            {% if subtasks %}
                                <p style="font-size: medium"><b>Subtasks: </b>
                                    {% for task in subtasks %}
                                        <a href="{% url 'tracker:task_info' task.id %}">{{ task.name }}, </a>
                                    {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                        <div class="col-md-6">
                            <p style="font-size: medium">
                                <b>Priority: </b>
                                <span class="{{ badge }}" style="font-size: 15px">{{ task.priority }}</span>
                            </p>
                            {% if task.start_date %}
                                <p style="font-size: medium">
                                    <b>Start date: </b>
                                    {{ task.start_date }}
                                </p>
                            {% endif %}
                            {% if task.start_time %}
                                <p style="font-size: medium">
                                    <b>Start time: </b>
                                    {{ task.start_time }}
                                </p>
                            {% endif %}
                            {% if task.end_date %}
                                <p style="font-size: medium">
                                    <b>End date: </b>
                                    {{ task.end_date }}
                                </p>
                            {% endif %}
                            {% if task.end_time %}
                                <p style="font-size: medium">
                                    <b>End time: </b>
                                    {{ task.end_time }}
                                </p>
                            {% endif %}
                            <p style="font-size: medium">
                                <b>Status: </b>
                                <span class="{{ status_badge }}" style="font-size: 15px">{{ status }}</span>
                            </p>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Manage Task</h3>
                    </div>
                    <div class="box-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {% if not archive and task.type == 2 %}
                                <button type="submit" class="btn btn-block btn-primary" name="start_again">Start again
                                </button>
                            {% endif %}
                            <a href="{% url 'tracker:task_delete' task.id %}"
                               class="btn btn-block btn-danger">Delete</a>
                            {% if not archive %}
                                <button type="submit" class="btn btn-block btn-success" name="cancel_task"
                                        style="margin-top: 20px">DONE
                                </button>
                            {% endif %}
                        </form>
                    </div>
                </div>
                {% if task.type == 1 %}
                    {% if not archive %}
                        {% if task.assosiated_task_id == None and task.is_subtask == 0 and task.parent_task_id == None and task.is_parent == None %}
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Set subtask</h3>
                                </div>
                                <div class="box-body">
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <label class="btn-block">
                                            <select style="display: inline-block"
                                                    class="form-control js-example-basic-single"
                                                    name="add_subtask" id="add_subtask">
                                                {% for task in task_list %}
                                                    <option value="{{ task.id }}">{{ task.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </label>
                                        <button type="submit" name='remove_from_project'
                                                class="btn btn-primary btn-block">Add
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Set assosiated task</h3>
                                </div>
                                <div class="box-body">
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <label class="btn-block">
                                            <select style="display: inline-block"
                                                    class="form-control js-example-basic-single"
                                                    name="add_assosiate" id="add_assosiate">
                                                {% for task in task_list %}
                                                    <option value="{{ task.id }}">{{ task.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </label>
                                        <button type="submit" name='remove_from_project'
                                                class="btn btn-primary btn-block">Set
                                        </button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

templates/tasks/list.html
{% extends 'adminlte/base.html' %}

{% block title %}List of Tasks{% endblock %}
{% load i18n static %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row col-md-3">
                <h1 class="page-header">List of tasks</h1>
                <a href="{% url 'tracker:task_create' %}"><button class="btn btn-primary btn-block btn-flat">Create task</button></a>
            </div>
        </div>
    </section>
    <div class="container-fluid">
        <section class="content">
            <div class="row">
                {% if not task_list %}
                    <h1 class="text-center">There is no tasks</h1>
                {% endif %}
                {% for task in task_list %}
                    <div class="col-md-6">
                        <div class="task" id="task.id">
                            {% if task.is_archive == 0 %}
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title"><a href="{% url 'tracker:task_info' task_id=task.id %}">{{ task.name }}</a></h3>
                            {% else %}
                                <div class="box box-success">
                                <div class="box-header with-border">
                                <h3 class="box-title"><a href="{% url 'tracker:task_info' task_id=task.id %}"><s>{{ task.name }}</s></a></h3>
                            {% endif %}
                                </div>
                                {% if task.desc %}
                                    <div class="box-body">
                                        <p class="info">{{ task.desc }}</p>
                                    </div>
                                {% endif %}
                                <div class="box-footer">
                                     <div class="row">
                                         <div class="col-md-4 pull-right">
                                             <a href="{% url 'tracker:task_info' task_id=task.id %}">
                                                 <button class="btn btn-primary btn-block btn-flat">More Info</button>
                                             </a>
                                         </div>
                                     </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock %}